# Generated by Django 5.2.1 on 2025-06-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=200)),
                ('urlProducto', models.CharField(max_length=1000)),
                ('precioProducto', models.IntegerField()),
                ('tipoProducto', models.CharField(max_length=50)),
            ],
        ),
    ]
