# Generated by Django 4.2.20 on 2025-07-04 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_veterinario_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='nombre_propietario',
        ),
        migrations.AddField(
            model_name='cita',
            name='propietario',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='store.usermascota'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NuevaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('tipo_mascota', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('motivo', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.usermascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.veterinario')),
            ],
        ),
    ]
